version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./static:/app/static
      - ./data:/app/data
    ports:
      - "8007:8000"
    environment:
      POSTGRES_HOST: rc1a-v996oj87q9dlvelr.mdb.yandexcloud.net
      POSTGRES_PORT: 6432
      POSTGRES_NAME: db1
      POSTGRES_USER: user1
    restart: unless-stopped

#  db:
#    image: postgres:13-alpine
#    env_file:
#      - .env
#    volumes:
#      - postgres_data:/var/lib/postgresql/data
#    restart: unless-stopped
#    healthcheck:
#      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
#      interval: 5s
#      timeout: 5s
#      retries: 5

volumes:
  postgres_data: